# Generated by Django 3.2 on 2022-12-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='artist',
            new_name='Author',
        ),
    ]
